### ISSUE TITLE
Error when firing bow, halved my fps and logged got spammed

### ISSUE THREAD

**Issue by BugmanBugman** [ArekkuusuJerii/BetterHurtTimer#11]
https://hatebin.com/kmsqaadvnb
My console got filled up with this after i shot a bow and got the achievement. FPS halved soon after.

**Comment by BunnyCinnamon** [comment]
It did that after hitting an entity? or while the arrow was on the air?

**Comment by BunnyCinnamon** [comment]
I honestly do not understand what went wrong, this shouldn't be possible...
what BHT version is this?

**Comment by BugmanBugman** [comment]
4.3.1.0

i'll try recreating it again. It did it when it hit an entity
