### ISSUE TITLE
Insane damage from the Wroughnaught Axe from Mowzie's Mobs

### ISSUE THREAD

**Issue by CalaMariGold** [ArekkuusuJerii/BetterHurtTimer#14]
The axe has a shift+right click ability and it's doing 8-12 damage 15 times in a second. We disabled iframes and attack speed for attacks but want this item specifically to have an iframe. How would we go about doing that?

**Comment by BunnyCinnamon** [comment]
Well, I could code something for that

**Comment by BunnyCinnamon** [comment]
another way is checking if the axe is doing a special kind of damage and use that to set an iframe

**Comment by BunnyCinnamon** [comment]
what minecraft version are you on? 1.12?

**Comment by CalaMariGold** [comment]
Mhm!

**Comment by BunnyCinnamon** [comment]
Done, try it out when you can
[https://github.com/ArekkuusuJerii/BetterHurtTimer/releases/tag/test](https://github.com/ArekkuusuJerii/BetterHurtTimer/releases/tag/test)

**Comment by BunnyCinnamon** [comment]
A bit of a warning though, because you disabled attack speed and iFrames for attacks, players will be able to hit entities as fast as they can click, even in the same frame, using macros.

I recommend adding a damageSource rule for player attacks: "player:false:0"
then remove "player" from the attackSources rules
this way they cannot spam attack to win on the same frame, as the damage has to be higher than the previous damage to register.
but it's alright

**Comment by BunnyCinnamon** [comment]
Right,
The new config option is called "itemSource"
use it like: "minecraft:iron_axe:0.5"

**Comment by BunnyCinnamon** [comment]
> 
> 
> A bit of a warning though, because you disabled attack speed and iFrames for attacks, players will be able to hit entities as fast as they can click, even in the same frame, using macros.
> 
> I recommend adding a damageSource rule for player attacks: "player:false:0"
> then remove "player" from the attackSources rules
> this way they cannot spam attack to win on the same frame, as the damage has to be higher than the previous damage to register.
> but it's alright

Actually don't do this, I think I forgot but if you do this then players won't be able to hit entities at the same time...

**Comment by CalaMariGold** [comment]
We use Better Combat Rebirthed, which makes it so that players can not attack while their attack speed is on cooldown. Also, this new version works perfectly, thank you so much <3

**Comment by CalaMariGold** [comment]
If you could upload the new jar on Curse, that would be great. Thank you!

**Comment by BunnyCinnamon** [comment]
Oh sure :>
