### ISSUE TITLE
Performant and Better Hurt Timer together break attacking enemies.

### ISSUE THREAD

**Issue by BugmanBugman** [ArekkuusuJerii/BetterHurtTimer#15]
https://github.com/someaddons/performant_issues/issues/71

**Comment by BunnyCinnamon** [comment]
By "most of the time " do you mean sometimes by random they don't get hurt? or that they only get hurt when they're not already being attacked?

**Comment by BugmanBugman** [comment]
Sometimes a hit gets through, but it isn’t by random. They’re basically immune to my attacks

Sent from my iPhone

On Jan 2, 2021, at 11:20 AM, Arekkuusu <notifications@github.com> wrote:

﻿

By "most of the time " do you mean sometimes by random they don't get hurt? or that they only get hurt when they're not already being attacked?

**Comment by BugmanBugman** [comment]
Might have to do with this https://github.com/someaddons/performant_issues/issues/69

**Comment by BunnyCinnamon** [comment]
Question, is this still happening?

**Comment by BugmanBugman** [comment]
Nope
