### ISSUE TITLE
Crash with first person model (they made a forge version)

### ISSUE THREAD

**Issue by Spoofygamer** [ArekkuusuJerii/BetterHurtTimer#17]
I told the first person dev, and they managed to fix the issue in you mod with one line change.

[crash-2021-01-19_16.47.37-client.txt](https://github.com/BunnyCinnamon/BetterHurtTimer/files/5838885/crash-2021-01-19_16.47.37-client.txt)

**Comment by tr7zw** [comment]
The first person dev here, it seems like a concurrent modification/race condition is happening inside the Object2ObjectArrayMap used in BHTAPI. The mods themselves are compatible(tried firstpersonmod + betterhurttimer + optifine), but somehow the setup in the crash report causes this issue.

**Comment by BunnyCinnamon** [comment]
> 
> 
> I told the first person dev, and they managed to fix the issue in you mod with one line change.
> 
> [crash-2021-01-19_16.47.37-client.txt](https://github.com/BunnyCinnamon/BetterHurtTimer/files/5838885/crash-2021-01-19_16.47.37-client.txt)

What was the change? :0

**Comment by BunnyCinnamon** [comment]
I think I know what it was, it could have been a mod triggering a config reload event on a thread during the initialization of the configs. It's literally using a CompletableFuture.

**Comment by BunnyCinnamon** [comment]
I can just mark it as synchronized...

**Comment by BunnyCinnamon** [comment]
Also idk why I used Object2ObjectArrayMap, I should've known the implementation is horrible for lookup, changing it for a HashMap.
