### ISSUE TITLE
Mixin Error 1.12.2

### ISSUE THREAD

**Issue by mxnmnm** [ArekkuusuJerii/BetterHurtTimer#3]
Looks like an issue related to mixins to have fun, the game didn't even show me the java screen and the log is screaming about mixin errors lol.
[latest.log](https://github.com/ArekkuusuJerii/BetterHurtTimer/files/4872137/latest.log)

Version 1.12.2-1.2.1.1

**Comment by mxnmnm** [comment]
If you need more info let me know

**Comment by BunnyCinnamon** [comment]
Ohh, what happens if you remove MixinTweaker?

**Comment by mxnmnm** [comment]
Uh mixintweaker? I don't think I have that installed unless another mod autoinstalled it.

**Comment by mxnmnm** [comment]
Unless you're talking about another mod that also uses mixins, in which case yea I have a few (vanilla fix and bewitchment right off the top of my head and probably several others)

**Comment by BunnyCinnamon** [comment]
Oh wait nvm I mixed up MixinBootstrap with MixinTweaker, remove MixinBootstrap if you have it :p

**Comment by mxnmnm** [comment]
Where would I find it?

**Comment by BunnyCinnamon** [comment]
In the mods folder, under the name of MixinBootstrap

**Comment by mxnmnm** [comment]
Yea that isn't in the mods folder

**Comment by mxnmnm** [comment]
I also removed the other folders that could've potentially had it inside.

**Comment by mxnmnm** [comment]
the issue still occurred so I'm not sure

**Comment by ACGaming** [comment]
https://paste.ubuntu.com/p/545wt2YmCF/
Can confirm this. Crash occurs with and without MixinBootstrap, no difference concerning the log.
Playing 1.12.2 with BetterHurtTimer-1.12.2-1.2.1.1.

**Comment by BunnyCinnamon** [comment]
Interesting, this happens even with just the two mods in...

**Comment by BunnyCinnamon** [comment]
The error is useless however, it does not really tell me what the exact issue is as the stacktrace (error) points out something that is not there in the code

**Comment by BunnyCinnamon** [comment]
This is a 1.12.2 error, 1.15 and 1.16 don't seem to have this issue, but I can tell this is caused by my mod. I'll mark it as a bug/crash

**Comment by BunnyCinnamon** [comment]
面白い！
