### ISSUE TITLE
1.16.1 breaks my game...(forge 32.0.70)

### ISSUE THREAD

**Issue by BunnyCinnamon** [ArekkuusuJerii/BetterHurtTimer#4]
aospirit: 1.16.1 breaks my game...(forge 32.0.70)

Not sure what is the problem here hmmm, need a crash log first to investigate.

**Comment by lag42** [comment]
i've been getting possibly the same issue, it crashes on world load with just BHT 1.16.1-3.3.0.0 and MixinBootstrap-1.0.3 on forge 32.0.75 which i'd say constitutes breaking my game

https://gist.github.com/lag42/9e9c58b75ebf5aed5f045af99eead312
