### ISSUE TITLE
Mekanism's Atomic Dissasembler deals 1 damage (instead of 20)

### ISSUE THREAD

**Issue by Krutoy242** [ArekkuusuJerii/BetterHurtTimer#5]
MC: 1.12.2
Forge: 14.23.5.2847
BHT: 1.3.0.0

<img src="https://i.imgur.com/mPyVLkA.png">

When hitting, Atomic Disassembler from  [Mekanism](https://www.curseforge.com/minecraft/mc-mods/mekanism) mod usually deals 20 constant damage, but with BHT only 1. 
Expected similar to hand attack, but with 20 damage.

Hit video: https://imgur.com/xIvdFgj

**Comment by BunnyCinnamon** [comment]
I found out why... and its not pretty.
Mekanism is hitting the same entity _twice_ in the same game update [here](https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/common/item/ItemAtomicDisassembler.java#L70), this is not possible under normal circumstances............. this is **incredibly wrong** on their part as hit damage is _NOT_ meant be applied like that, they should've made it an Additive Attribute like regular weapons do...... one bad thing about it is armor wears down FASTER if you do this (twice, once for the initial hit of 1dmg and once for the 19dmg).

I know how to fix it however and thinking about it this might not be the only mod that fucks up this bad, I will fix their mistake but in a way break other stuff on its course.

Thank you for the bug report :>

**Comment by BunnyCinnamon** [comment]
Expect a beta by tomorrow and sorry for the small rant 🧶

**Comment by Krutoy242** [comment]
Thank you for fast reaction!

**Comment by BunnyCinnamon** [comment]
Fixed.

**Comment by BunnyCinnamon** [comment]
1.12.2-1.3.0.1 is on curse now

**Comment by Krutoy242** [comment]
New fixes in one day! So fast, thank you. Gonna check out in few days.
