### ISSUE TITLE
Insta crash on launch

### ISSUE THREAD

**Issue by CmdrJane** [ArekkuusuJerii/BetterHurtTimer#6]
okay here it goes.
https://pastebin.com/n6MZruuy
game crash instantly on launch, only enderskills installed. However BetterHurtTimer causes a crash when it only mod installed.

Minecraft 1.12.2
Forge 14.23.5.2854

**Comment by BunnyCinnamon** [comment]
Yeah you also need BootstrapMixin https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap

**Comment by CmdrJane** [comment]
U joking? I'm on 1.12.2 IT ALLREADY HAVE BUILT IN MIXINS

**Comment by CmdrJane** [comment]
not mention that mod u linked doesn't have a version for 1.12.2

**Comment by CmdrJane** [comment]
okay i didnt know that mixin bootstrap is universal, its work now.thx
