### ISSUE TITLE
Crash on launch (after updated to 1.3.0.5)

### ISSUE THREAD

**Issue by Krutoy242** [ArekkuusuJerii/BetterHurtTimer#7]
MC 1.12.2

Game crushes even before MC window appears. Happens only when updating from `1.3.0.4` to `1.3.0.5`

[debug.log](https://gist.github.com/Krutoy242/1f4b3f5a51ea34af4c91678ef5b2c6b0)

**Comment by BunnyCinnamon** [comment]
Ah yeah, use the non-Bukkit version
https://www.curseforge.com/minecraft/mc-mods/better-hurt-timer/files/3044485

**Comment by Krutoy242** [comment]
Im not chosing version manually. I just press "Update" on my Twitch Luncher.
Is there possible way to not manually load your mod?

**Comment by BunnyCinnamon** [comment]
No :<

And the error is caused by forge being dumb.
