### ISSUE TITLE
Crash sponge server

### ISSUE THREAD

**Issue by HuangAdam** [ArekkuusuJerii/BetterHurtTimer#8]
# Only one mod!
![随意](https://user-images.githubusercontent.com/46439030/92507906-4c477d80-f23a-11ea-8ad1-055275dbd4c4.png)

[latest.log](https://github.com/ArekkuusuJerii/BetterHurtTimer/files/5189935/latest.log)
No crash-report

**Comment by HuangAdam** [comment]
MC version: 1.12.2
mod version: 1.3.0.5
Forge version: 2854

**Comment by BunnyCinnamon** [comment]
You need the sponge version of the mod, its on curseforge

**Comment by HuangAdam** [comment]
I have tried the both. It show me the same thing.
So which one is sponge version mod?

**Comment by HuangAdam** [comment]
![both](https://user-images.githubusercontent.com/46439030/92652785-01a03100-f320-11ea-877f-0960297f520b.png)

**Comment by BunnyCinnamon** [comment]
Ah, the bukkit one

**Comment by BunnyCinnamon** [comment]
It probably did not work either did it? Hmmm

**Comment by HuangAdam** [comment]
Yeah
Mod with bukkit: 
[Bukkit.log](https://github.com/ArekkuusuJerii/BetterHurtTimer/files/5205710/Bukkit.log)

No bukkit mod: 
[latest.log](https://github.com/ArekkuusuJerii/BetterHurtTimer/files/5205711/latest.log)
